# This configuration is used for testing the tcp sampler

[general]
listen = "0.0.0.0:4242"
logging = "debug"
interval = 1000
window = 5

# Per-sampler configuration sections
[samplers]
# The tcp sampler provides telemetry about tcp traffic
[samplers.tcp]
# Controls whether to use this sampler
enabled = true

# Enable BPF sampling
bpf = true

statistics = [
	"tcp/srtt",
]
