# This example is for tcp sampler

# General configuration
[general]
# Sets the socket address for Rezolus to listen on. This is a required parameter
listen = "0.0.0.0:4242"

# Specify the logging level: error, info, debug, trace,
logging = "trace"

# The default interval, in milliseconds, for all samplers
interval = 10000

# The default window for percentiles in seconds. Samples older than this will
# age-out of the histograms.
window = 10

# The number of worker threads which are used to run samplers. This should be
# increased if the process is CPU bound and falling behind when running a large
# number of samplers. Individual samplers cannot be running concurrently on
# multiple workers, so increasing this will not help if a particular sampler is
# falling behind due to its interval being too short, but would allow for other
# samplers to run in parallel.
threads = 1


[samplers]
[samplers.tcp]
enabled = true
bpf = true

# Sampling interval, in milliseconds, for this sampler
# interval = 1000

# The set of exported statistics may be limited by specifying them, otherwise
# the complete set of statistics will be exported.
statistics = [
	"tcp/receive/segment",
	"tcp/transmit/segment",
	"tcp/connection/accepted",
	"tcp/connection/initiated",
]